// required: associates our `main.dart` with the code generated by Freezed
import 'package:freezed_annotation/freezed_annotation.dart';

part 'anon_file_upload.freezed.dart';
part 'anon_file_upload.g.dart';

@freezed
class AnonFileUploadEvent with _$AnonFileUploadEvent {
  const factory AnonFileUploadEvent({
    double? progress,
    AnonFileUploadResponse? response,
  }) = _AnonFileUploadEvent;

  factory AnonFileUploadEvent.fromJson(Map<String, Object?> json) =>
      _$AnonFileUploadEventFromJson(json);
}

@freezed
class AnonFileUploadResponse with _$AnonFileUploadResponse {
  const factory AnonFileUploadResponse({
    bool? status,
    AnonFileUploadResponseData? data,
  }) = _AnonFileUploadResponse;

  factory AnonFileUploadResponse.fromJson(Map<String, Object?> json) =>
      _$AnonFileUploadResponseFromJson(json);
}

@freezed
class AnonFileUploadResponseData with _$AnonFileUploadResponseData {
  const factory AnonFileUploadResponseData({
    AnonFile? file,
  }) = _AnonFileUploadResponseData;

  factory AnonFileUploadResponseData.fromJson(Map<String, Object?> json) =>
      _$AnonFileUploadResponseDataFromJson(json);
}

@freezed
class AnonFile with _$AnonFile {
  const factory AnonFile({
    AnonFileUrl? url,
    AnonFileMetadata? metadata,
  }) = _AnonFile;

  factory AnonFile.fromJson(Map<String, Object?> json) =>
      _$AnonFileFromJson(json);
}

@freezed
class AnonFileUrl with _$AnonFileUrl {
  const factory AnonFileUrl({
    String? full,
    String? short,
  }) = _AnonFileUrl;

  factory AnonFileUrl.fromJson(Map<String, Object?> json) =>
      _$AnonFileUrlFromJson(json);
}

@freezed
class AnonFileMetadata with _$AnonFileMetadata {
  const factory AnonFileMetadata({
    String? id,
    String? name,
    AnonFileSize? size,
  }) = _AnonFileMetadata;

  factory AnonFileMetadata.fromJson(Map<String, Object?> json) =>
      _$AnonFileMetadataFromJson(json);
}

@freezed
class AnonFileSize with _$AnonFileSize {
  const factory AnonFileSize({
    int? bytes,
    String? readable,
  }) = _AnonFileSize;

  factory AnonFileSize.fromJson(Map<String, Object?> json) =>
      _$AnonFileSizeFromJson(json);
}
